import React, { useEffect, useRef, useState } from 'react';
import { Warehouse, Plus, Search, Pencil, MoreVertical, ChevronRight, HelpCircle, ArrowRightLeft, History, ShieldCheck } from 'lucide-react';
import type { Location, LocationEvent } from '../types';
import { auditStorage, auditLocationRegistry, isStorageAdmin, type StorageCommand, type StorageState } from '../utils/storageModel';
import { createEquipmentDestinationResolver } from '../utils/equipmentDestinations';
import { StorageDialog, TransferDialog, ReviewDestinationDialog, LocationHistory, storageInput, storagePrimary } from './StorageControls';
import HelpGuideModal from './HelpGuideModal';
import { useNotifications } from './NotificationProvider';

const helpSteps = [
  { title: 'Cadastre espaços reais', description: 'Um local representa um almoxarifado, depósito ou outro espaço físico da empresa. Ele aparece mesmo vazio. Máquinas e parceiros continuam nos seus próprios cadastros.', icon: Warehouse, accent: 'bg-emerald-600 text-white' },
  { title: 'Escolha um padrão', description: 'O administrador pode definir um local ativo como sugestão inicial. Confira o recebimento em cada operação: padrão não significa destino obrigatório.', icon: ShieldCheck, accent: 'bg-slate-900 text-white' },
  { title: 'Movimente pelo fluxo correto', description: 'Transfira entre armazenamentos pela aba Equipamentos. Para máquinas use O.S.; para parceiros use empréstimos ou manutenção. Agendar e iniciar uma O.S. não movimenta fisicamente o equipamento.', icon: ArrowRightLeft, accent: 'bg-emerald-600 text-white' },
  { title: 'Histórico e inativação', description: 'Cada transferência registra origem, destino, usuário e operação. Não excluímos locais: só é possível inativar após retirar os equipamentos, resolver O.S. pendentes e escolher outro padrão.', icon: History, accent: 'bg-slate-900 text-white' },
  { title: 'Conferência de dados antigos', description: 'Exporte o relatório e faça backup antes de regularizar. Não deduzimos almoxarifado quando falta informação. Registros com operações em aberto precisam ser resolvidos no fluxo correspondente.', icon: ShieldCheck, accent: 'bg-amber-600 text-white' },
];

export default function StorageLocationsTab({ state, events, role, onCommand, onViewEquipment }: { state: StorageState; events: LocationEvent[]; role: string; onCommand: (command: StorageCommand) => Promise<void>; onViewEquipment: (id: string) => void }) {
  const [query, setQuery] = useState(''); const [active, setActive] = useState('active'); const [selectedId, setSelectedId] = useState<string>();
  const [editing, setEditing] = useState<Location>(); const [tab, setTab] = useState('dados'); const [help, setHelp] = useState(false);
  const [menu, setMenu] = useState(false); const menuRef = useRef<HTMLDivElement>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [selection, setSelection] = useState<string[]>([]); const [transfer, setTransfer] = useState(false); const [review, setReview] = useState<string>(); const [audit, setAudit] = useState(false);
  const { confirmDialog, showToast } = useNotifications(); const admin = isStorageAdmin(role);
  const selected = state.locations.find(item => item.id === selectedId);
  const resolve = createEquipmentDestinationResolver(state.machines, state.locations, state.maintenances);
  const inventory = (id: string) => state.components.filter(item => item.active !== false && resolve(item).key === `internal:location:${id}`);
  const issues = auditStorage(state);
  const locations = state.locations.filter(item => item.kind === 'INTERNAL' && (active === 'all' || item.isActive === (active === 'active')) && `${item.name} ${item.code || ''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b) => a.name.localeCompare(b.name, 'pt-BR'));
  useEffect(() => { if (!menu) return; const outside = (event: PointerEvent) => { if (!menuRef.current?.contains(event.target as Node)) setMenu(false); }; document.addEventListener('pointerdown', outside); return () => document.removeEventListener('pointerdown', outside); }, [menu]);
  const run = async (command: StorageCommand) => { setBusy(true); setError(''); try { await onCommand(command); showToast('success', 'Alteração salva.'); return true; } catch (err) { setError(err instanceof Error ? err.message : 'Não foi possível salvar.'); return false; } finally { setBusy(false); } };
  const exportAudit = () => { const blob = new Blob([JSON.stringify({ generatedAt: new Date().toISOString(), equipmentIssues: issues, locationIssues: auditLocationRegistry(state) }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'conferencia-locais.json'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  return <div className="space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><h1 className="text-xl font-bold text-slate-900">Locais de armazenamento</h1><p className="mt-1 text-sm text-slate-500">Organize os espaços e acompanhe entradas e saídas.</p></div><div className="flex gap-2"><button onClick={() => setHelp(true)} aria-label="Ajuda sobre armazenamento" className="flex h-11 w-11 items-center justify-center rounded-xl border border-slate-200 text-slate-500"><HelpCircle size={18} /></button>{admin && <button className={storagePrimary + ' flex items-center gap-2'} onClick={() => { setError(''); setEditing({ id: crypto.randomUUID(), name: '', kind: 'INTERNAL', isActive: true }); }}><Plus size={18} />Novo</button>}</div></header>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="flex flex-wrap items-center gap-3 border-b border-slate-100 p-4"><label className="relative min-w-40 flex-1"><span className="sr-only">Buscar local</span><Search size={17} className="absolute left-3 top-3.5 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar nome ou código" className={storageInput + ' pl-9'} /></label><select aria-label="Situação dos locais" value={active} onChange={event => setActive(event.target.value)} className={storageInput + ' !w-auto'}><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="all">Todos</option></select><span className="text-xs text-slate-500">{locations.length} local(is)</span></div>
      <div className="divide-y divide-slate-100">{locations.map(location => <button key={location.id} onClick={() => { setSelectedId(location.id); setTab('dados'); setSelection([]); setError(''); }} className="flex w-full items-center gap-3 p-4 text-left hover:bg-slate-50 focus-visible:outline-emerald-600"><span className="rounded-xl bg-slate-100 p-3 text-slate-500"><Warehouse size={20} /></span><div className="min-w-0 flex-1"><p className="font-semibold text-slate-900">{location.name}</p><p className="mt-1 text-xs text-slate-500">{location.code ? `${location.code} · ` : ''}{inventory(location.id).length} equipamentos · {location.isActive ? 'Ativo' : 'Inativo'}{state.settings.defaultLocationId === location.id ? ' · Local padrão' : ''}</p></div><ChevronRight size={18} className="text-slate-400" /></button>)}</div>
      {!locations.length && <p className="p-8 text-center text-sm text-slate-500">Nenhum local encontrado. {admin ? 'Use Novo para cadastrar um espaço de armazenamento.' : 'Peça ao administrador para cadastrar um espaço.'}</p>}
    </section>
    {admin && <section className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><button onClick={() => setAudit(!audit)} className="min-h-11 text-sm font-semibold text-slate-700">Conferência de destinos · {issues.length} equipamento(s)</button><button onClick={exportAudit} className="min-h-11 text-xs font-semibold text-emerald-700">Exportar relatório</button></div>{audit && <div className="space-y-3 border-t border-slate-100 pt-3"><p className="text-xs text-slate-500">Revise o relatório e faça backup antes de corrigir. Nada é alterado automaticamente.</p>{issues.map(({ component, issues: reasons }) => <div key={component.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3"><div className="min-w-0 flex-1 text-sm"><strong>{component.name}</strong><p className="text-xs text-slate-500">S/N {component.serialNumber} · {reasons.join(' · ')}</p></div><button onClick={async () => { if (await confirmDialog({ title: 'Conferir destino', message: 'Confirma que há backup e que você verificou fisicamente onde este equipamento está?' })) setReview(component.id); }} className="min-h-11 text-xs font-semibold text-emerald-700 disabled:text-slate-400">Conferir destino</button></div>)}</div>}</section>}
    {selected && !editing && <StorageDialog title={selected.name} busy={busy} onClose={() => setSelectedId(undefined)}>
      <div className="mb-4 flex items-center justify-between gap-3"><p className="text-xs text-slate-500">{selected.isActive ? 'Ativo' : 'Inativo'}{state.settings.defaultLocationId === selected.id ? ' · Padrão' : ''}</p>{admin && <div className="flex gap-1"><button aria-label="Editar local" title="Editar local" onClick={() => setEditing({ ...selected })} className="flex h-11 w-11 items-center justify-center rounded-xl text-slate-500 hover:bg-slate-50"><Pencil size={17} /></button><div ref={menuRef} className="relative"><button aria-label="Mais opções" aria-expanded={menu} onClick={() => setMenu(!menu)} className="flex h-11 w-11 items-center justify-center rounded-xl text-slate-500"><MoreVertical size={18} /></button>{menu && <div className="absolute right-0 top-full z-10 w-52 rounded-xl border border-slate-200 bg-white p-1 shadow-lg"><button disabled={busy} onClick={async () => { setMenu(false); if (await confirmDialog({ title: selected.isActive ? 'Inativar local' : 'Reativar local', message: 'O histórico será preservado.' })) await run({ type: 'saveLocation', location: { ...selected, isActive: !selected.isActive } }); }} className="min-h-11 w-full rounded-lg px-3 text-left text-sm text-rose-600">{selected.isActive ? 'Inativar' : 'Reativar'}</button></div>}</div></div>}</div>
      <nav aria-label="Resumo do local" className="mb-4 flex border-b border-slate-200">{[['dados','Dados'],['equipamentos','Equipamentos'],['historico','Histórico']].map(([id,label]) => <button key={id} onClick={() => setTab(id)} aria-current={tab === id ? 'page' : undefined} className={`min-h-11 flex-1 border-b-2 px-2 text-xs font-semibold ${tab === id ? 'border-emerald-600 text-emerald-700' : 'border-transparent text-slate-500'}`}>{label}</button>)}</nav>
      {tab === 'dados' && <div className="space-y-4 text-sm"><p><span className="block text-xs text-slate-500">Código</span>{selected.code || 'Não informado'}</p><p><span className="block text-xs text-slate-500">Endereço / referência</span>{selected.address || 'Não informado'}</p>{selected.notes && <p>{selected.notes}</p>}{admin && selected.isActive && state.settings.defaultLocationId !== selected.id && <button disabled={busy} onClick={() => run({ type: 'default', locationId: selected.id })} className="min-h-11 text-sm font-semibold text-emerald-700">Definir como local padrão</button>}</div>}
      {tab === 'equipamentos' && <div className="space-y-3"><button onClick={() => onViewEquipment(selected.id)} className="min-h-11 text-sm font-semibold text-emerald-700">Ver equipamentos na listagem →</button>{inventory(selected.id).map(item => <label key={item.id} className="flex min-h-14 items-center gap-3 rounded-xl border border-slate-100 p-3"><input type="checkbox" checked={selection.includes(item.id)} onChange={event => setSelection(event.target.checked ? [...selection, item.id] : selection.filter(id => id !== item.id))} /><span className="text-sm">{item.name}<span className="block text-xs text-slate-500">S/N {item.serialNumber} · {item.status}</span></span></label>)}<button disabled={!selection.length} onClick={() => setTransfer(true)} className={storagePrimary}>Transferir selecionados ({selection.length})</button></div>}
      {tab === 'historico' && <LocationHistory events={events.filter(item => item.from.locationId === selected.id || item.to.locationId === selected.id)} />}
      {error && <p role="alert" className="mt-3 text-sm text-rose-600">{error}</p>}
    </StorageDialog>}
    {editing && <StorageDialog title={state.locations.some(item => item.id === editing.id) ? 'Editar local' : 'Novo local'} busy={busy} onClose={() => setEditing(undefined)} actions={<button form="storage-location-form" disabled={busy} className={storagePrimary}>{busy ? 'Salvando…' : 'Salvar local'}</button>}>
      <form id="storage-location-form" className="space-y-4" onSubmit={async event => { event.preventDefault(); if (await run({ type: 'saveLocation', location: editing })) setEditing(undefined); }}>
        <label className="block text-xs font-semibold text-slate-600">Nome *<input autoFocus required maxLength={120} value={editing.name} onChange={event => setEditing({ ...editing, name: event.target.value })} className={storageInput + ' mt-2'} placeholder="Ex.: Depósito da oficina" /></label>
        <label className="block text-xs font-semibold text-slate-600">Código (opcional)<input maxLength={40} value={editing.code || ''} onChange={event => setEditing({ ...editing, code: event.target.value })} className={storageInput + ' mt-2'} /></label>
        <label className="block text-xs font-semibold text-slate-600">Endereço / referência<input maxLength={512} value={editing.address || ''} onChange={event => setEditing({ ...editing, address: event.target.value })} className={storageInput + ' mt-2'} /></label>
        <label className="block text-xs font-semibold text-slate-600">Observações<textarea maxLength={512} value={editing.notes || ''} onChange={event => setEditing({ ...editing, notes: event.target.value })} className={storageInput + ' mt-2 min-h-24'} /></label>
        {error && <p role="alert" className="text-sm text-rose-600">{error}</p>}
      </form>
    </StorageDialog>}
    {review && state.components.find(item => item.id === review) && <ReviewDestinationDialog component={state.components.find(item => item.id === review)!} state={state} onCommand={onCommand} onClose={() => setReview(undefined)} />}
    {transfer && <TransferDialog components={state.components.filter(item => selection.includes(item.id))} locations={state.locations} defaultId={state.settings.defaultLocationId} onClose={() => { setTransfer(false); setReview(undefined); }} onTransfer={async (componentIds, locationId, notes) => { await onCommand({ type: 'transfer', componentIds, locationId, notes }); setSelection([]); }} />}
    <HelpGuideModal open={help} onClose={() => setHelp(false)} title="Locais de armazenamento" steps={helpSteps} />
  </div>;
}
